import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: "#131313",
        "inverse-surface": "#e5e2e1",
        "surface-variant": "#353534",
        "surface-bright": "#3a3939",
        "surface-dim": "#131313",
        "surface-tint": "#adc6ff",
        "surface-container-lowest": "#0e0e0e",
        "surface-container-low": "#1c1b1b",
        "surface-container": "#201f1f",
        "surface-container-high": "#2a2a2a",
        "surface-container-highest": "#353534",
        background: "#131313",
        "on-background": "#e5e2e1",
        "on-surface": "#e5e2e1",
        "on-surface-variant": "#c2c6d6",
        "inverse-on-surface": "#313030",
        outline: "#8c909f",
        "outline-variant": "#424754",
        primary: "#adc6ff",
        "primary-container": "#4d8eff",
        "primary-fixed": "#d8e2ff",
        "primary-fixed-dim": "#adc6ff",
        "on-primary": "#002e6a",
        "on-primary-container": "#00285d",
        "on-primary-fixed": "#001a42",
        "on-primary-fixed-variant": "#004395",
        "inverse-primary": "#005ac2",
        secondary: "#4edea3",
        "secondary-container": "#00a572",
        "secondary-fixed": "#6ffbbe",
        "secondary-fixed-dim": "#4edea3",
        "on-secondary": "#003824",
        "on-secondary-container": "#00311f",
        "on-secondary-fixed": "#002113",
        "on-secondary-fixed-variant": "#005236",
        tertiary: "#ffb95f",
        "tertiary-container": "#ca8100",
        "tertiary-fixed": "#ffddb8",
        "tertiary-fixed-dim": "#ffb95f",
        "on-tertiary": "#472a00",
        "on-tertiary-container": "#3e2400",
        "on-tertiary-fixed": "#2a1700",
        "on-tertiary-fixed-variant": "#653e00",
        error: "#ffb4ab",
        "error-container": "#93000a",
        "on-error": "#690005",
        "on-error-container": "#ffdad6",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      fontFamily: {
        sans: ["var(--font-inter)", "Inter", "system-ui", "sans-serif"],
        mono: ["var(--font-mono)", "JetBrains Mono", "ui-monospace", "monospace"],
        "headline-lg": ["var(--font-inter)", "Inter"],
        "headline-xl": ["var(--font-inter)", "Inter"],
        "body-md": ["var(--font-inter)", "Inter"],
        "mono-label": ["var(--font-mono)", "JetBrains Mono"],
        "mono-code": ["var(--font-mono)", "JetBrains Mono"],
      },
      fontSize: {
        "headline-xl": [
          "48px",
          { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "headline-lg": ["32px", { lineHeight: "1.2", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "mono-label": ["11px", { lineHeight: "1.0", fontWeight: "500" }],
        "mono-code": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
      },
      spacing: {
        gutter: "16px",
        unit: "4px",
        "margin-mobile": "16px",
        "margin-desktop": "32px",
      },
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "gradient-conic":
          "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
        "engine-grid":
          "linear-gradient(rgba(255,255,255,0.03) 1px, transparent 1px), linear-gradient(90deg, rgba(255,255,255,0.03) 1px, transparent 1px)",
      },
      backgroundSize: {
        "grid-32": "32px 32px",
      },
      transitionTimingFunction: {
        "in-out-expo": "cubic-bezier(0.19, 1, 0.22, 1)",
      },
      keyframes: {
        "scan-x": {
          "0%": { transform: "translateX(-100%)" },
          "100%": { transform: "translateX(200%)" },
        },
      },
      animation: {
        "scan-x": "scan-x 2s ease-in-out infinite",
      },
    },
  },
  plugins: [],
};
export default config;
